-- ============================================================
-- AVATAR — Giai đoạn 5: HOÀN THIỆN SỔ QUỸ THU – CHI
--   1) Số phiếu chuẩn, tự sinh theo cơ sở + tháng (PT-02-2607-001)
--   2) Người nộp / người nhận tiền tách khỏi người lập phiếu
--   3) Hình thức thanh toán: tiền mặt / chuyển khoản
--   4) Chốt sổ theo tháng: kỳ đã chốt thì KHÓA, không ai sửa được
-- Chạy 1 lần trong Supabase → SQL Editor → Run. An toàn chạy lại nhiều lần.
-- ============================================================

-- ---------- 1) CÁC CỘT MỚI CỦA PHIẾU THU / CHI ----------
alter table public.so_quy add column if not exists so_phieu   text;   -- số hiệu chứng từ
alter table public.so_quy add column if not exists nguoi_nop  text;   -- người nộp tiền (phiếu thu) / người nhận tiền (phiếu chi)
alter table public.so_quy add column if not exists hinh_thuc  text;   -- 'tien_mat' | 'chuyen_khoan'
alter table public.so_quy add column if not exists gv_id      int;    -- phiếu chi lương gắn với giáo viên nào (để đối chiếu công)
alter table public.so_quy add column if not exists ky_luong   text;   -- kỳ lương 'YYYY-MM' của phiếu chi lương

update public.so_quy set hinh_thuc = 'tien_mat' where hinh_thuc is null;

-- ---------- 2) TỰ SINH SỐ PHIẾU ----------
-- Mẫu: PT-<mã cơ sở 2 số>-<YYMM>-<số thứ tự 3 số>
--   PT = phiếu thu, PC = phiếu chi. Số thứ tự đếm riêng theo cơ sở + tháng + loại,
--   nên mỗi cơ sở có một dãy số liên tục, không nhảy cóc theo mã trong CSDL.
create or replace function public.gen_so_phieu()
returns trigger language plpgsql security definer set search_path = public as $$
declare
  v_prefix text;
  v_ym     text;
  v_seq    int;
begin
  if new.so_phieu is not null and btrim(new.so_phieu) <> '' then
    return new;                                    -- đã có số (nhập tay / chuyển dữ liệu cũ) thì giữ nguyên
  end if;
  v_prefix := case when new.loai = 'thu' then 'PT' else 'PC' end;
  v_ym     := to_char(new.ngay, 'YYMM');
  select coalesce(max(
           nullif(regexp_replace(so_phieu, '^.*-', ''), '')::int
         ), 0) + 1
    into v_seq
    from public.so_quy
   where coso_id = new.coso_id
     and loai    = new.loai
     and so_phieu like v_prefix || '-' || lpad(new.coso_id::text, 2, '0') || '-' || v_ym || '-%';
  new.so_phieu := v_prefix || '-' || lpad(new.coso_id::text, 2, '0') || '-' || v_ym || '-' || lpad(v_seq::text, 3, '0');
  return new;
end $$;

drop trigger if exists so_quy_gen_so_phieu on public.so_quy;
create trigger so_quy_gen_so_phieu
  before insert on public.so_quy
  for each row execute function public.gen_so_phieu();

-- Điền số phiếu cho các phiếu CŨ (theo thứ tự ngày, giữ đúng trình tự sổ)
do $$
declare r record; v_seq int; v_key text; v_last text := '';
begin
  for r in
    select id, loai, coso_id, ngay
      from public.so_quy
     where so_phieu is null
     order by coso_id, loai, to_char(ngay,'YYMM'), ngay, id
  loop
    v_key := r.coso_id || '|' || r.loai || '|' || to_char(r.ngay,'YYMM');
    if v_key <> v_last then v_seq := 0; v_last := v_key; end if;
    v_seq := v_seq + 1;
    update public.so_quy
       set so_phieu = (case when r.loai='thu' then 'PT' else 'PC' end)
                      || '-' || lpad(r.coso_id::text,2,'0')
                      || '-' || to_char(r.ngay,'YYMM')
                      || '-' || lpad(v_seq::text,3,'0')
     where id = r.id;
  end loop;
end $$;

create index if not exists so_quy_sophieu_idx on public.so_quy(so_phieu);

-- ---------- 3) BẢNG CHỐT SỔ THEO THÁNG ----------
-- Mỗi cơ sở + mỗi kỳ (YYYY-MM) chốt một lần. Đã chốt = khóa mọi thao tác
-- thêm / sửa / xóa phiếu trong kỳ đó (kể cả phiếu thu học phí tự sinh).
create table if not exists public.chot_so_quy (
  id       bigint generated by default as identity primary key,
  coso_id  int  not null,
  ky       text not null,                       -- 'YYYY-MM'
  tong_thu numeric default 0,
  tong_chi numeric default 0,
  ton_cuoi numeric default 0,
  chot_at  timestamptz default now(),
  chot_by  uuid,
  ghi_chu  text,
  unique (coso_id, ky)
);
create index if not exists chot_so_quy_idx on public.chot_so_quy(coso_id, ky);
alter table public.chot_so_quy enable row level security;

-- Ai cũng XEM được kỳ đã chốt của phạm vi mình; chỉ QUẢN TRỊ được chốt / mở khóa.
drop policy if exists chot_sel on public.chot_so_quy;
drop policy if exists chot_ins on public.chot_so_quy;
drop policy if exists chot_upd on public.chot_so_quy;
drop policy if exists chot_del on public.chot_so_quy;
create policy chot_sel on public.chot_so_quy for select to authenticated
  using (my_role()='admin' or (my_role()='owner' and coso_id=my_coso()));
create policy chot_ins on public.chot_so_quy for insert to authenticated
  with check (my_role()='admin');
create policy chot_upd on public.chot_so_quy for update to authenticated
  using (my_role()='admin') with check (my_role()='admin');
create policy chot_del on public.chot_so_quy for delete to authenticated
  using (my_role()='admin');

-- Hàm: kỳ của phiếu này đã chốt chưa?
create or replace function public.is_ky_chot(p_coso_id int, p_ngay date)
returns boolean language sql stable security definer set search_path = public as $$
  select exists(
    select 1 from public.chot_so_quy
     where coso_id = p_coso_id and ky = to_char(p_ngay, 'YYYY-MM')
  )
$$;

-- ---------- 4) KHÓA GHI SỔ KHI KỲ ĐÃ CHỐT ----------
-- Khác với chốt ca dạy (admin vẫn sửa được): sổ quỹ đã chốt thì KHÓA VỚI MỌI VAI TRÒ,
-- muốn sửa buộc phải Mở khóa kỳ đó trước — đúng nguyên tắc kế toán.
drop policy if exists so_quy_sel on public.so_quy;
drop policy if exists so_quy_ins on public.so_quy;
drop policy if exists so_quy_upd on public.so_quy;
drop policy if exists so_quy_del on public.so_quy;
create policy so_quy_sel on public.so_quy for select to authenticated
  using (my_role()='admin' or (my_role()='owner' and coso_id=my_coso()));
create policy so_quy_ins on public.so_quy for insert to authenticated
  with check ((my_role()='admin' or (my_role()='owner' and coso_id=my_coso()))
              and not is_ky_chot(coso_id, ngay));
create policy so_quy_upd on public.so_quy for update to authenticated
  using ((my_role()='admin' or (my_role()='owner' and coso_id=my_coso()))
         and not is_ky_chot(coso_id, ngay))
  with check ((my_role()='admin' or (my_role()='owner' and coso_id=my_coso()))
              and not is_ky_chot(coso_id, ngay));
create policy so_quy_del on public.so_quy for delete to authenticated
  using ((my_role()='admin' or (my_role()='owner' and coso_id=my_coso()))
         and not is_ky_chot(coso_id, ngay));

-- ---------- 5) BẬT REALTIME CHO BẢNG CHỐT SỔ ----------
do $$ begin
  begin execute 'alter publication supabase_realtime add table public.chot_so_quy';
  exception when others then null; end;
end $$;

-- ============================================================
-- XONG. Bấm Run rồi tải lại web (Ctrl+F5).
-- Kiểm tra nhanh:
--   select so_phieu, ngay, loai, so_tien, nguoi_nop, hinh_thuc
--     from public.so_quy order by ngay desc limit 20;
-- ============================================================
