-- ============================================================
-- AVATAR — Giai đoạn 4: LUỒNG DUYỆT ĐIỂM DANH
-- GV điểm danh → Lễ tân ĐỐI SOÁT → Quản trị CHỐT (khóa số liệu ca đó).
-- Chạy 1 lần trong SQL Editor -> Run. An toàn chạy lại nhiều lần.
-- ============================================================

-- 1) Bảng trạng thái duyệt cho mỗi CA DẠY (1 lớp + 1 ngày)
create table if not exists public.duyet_diem_danh (
  id bigint generated by default as identity primary key,
  lop_id int not null,
  ngay   date not null,
  coso_id int not null,
  trang_thai text not null default 'cho_duyet'
    check (trang_thai in ('cho_duyet','da_doi_soat','da_chot')),
  gv_gui_at  timestamptz default now(),   -- lúc GV gửi đối soát
  letan_at   timestamptz,                 -- lúc lễ tân chấp nhận
  admin_at   timestamptz,                 -- lúc quản trị chốt
  updated_at timestamptz default now(),
  unique (lop_id, ngay)
);
create index if not exists ddd_coso_idx on public.duyet_diem_danh(coso_id);
alter table public.duyet_diem_danh enable row level security;

-- 2) Hàm: ca này đã CHỐT chưa (dùng để khóa sửa điểm danh)
create or replace function public.is_ca_chot(p_lop_id int, p_ngay date)
returns boolean language sql stable security definer set search_path = public as $$
  select exists(select 1 from public.duyet_diem_danh
                 where lop_id = p_lop_id and ngay = p_ngay and trang_thai = 'da_chot')
$$;

-- 3) RLS cho bảng duyệt
--    xem: admin / owner cơ sở / teacher lớp mình
--    thêm: các vai trò trên (GV gửi đối soát, tạo dòng cho_duyet)
--    sửa: admin mọi lúc; owner khi CHƯA chốt (để đối soát); teacher chỉ khi còn 'cho_duyet'
--    xóa: chỉ admin
drop policy if exists ddd_sel on public.duyet_diem_danh;
drop policy if exists ddd_ins on public.duyet_diem_danh;
drop policy if exists ddd_upd on public.duyet_diem_danh;
drop policy if exists ddd_del on public.duyet_diem_danh;
create policy ddd_sel on public.duyet_diem_danh for select to authenticated
  using (my_role()='admin' or (my_role()='owner' and coso_id=my_coso()) or (my_role()='teacher' and is_my_lop(lop_id)));
create policy ddd_ins on public.duyet_diem_danh for insert to authenticated
  with check (my_role()='admin' or (my_role()='owner' and coso_id=my_coso()) or (my_role()='teacher' and is_my_lop(lop_id)));
create policy ddd_upd on public.duyet_diem_danh for update to authenticated
  using (
    my_role()='admin'
    or (my_role()='owner'   and coso_id=my_coso()   and trang_thai <> 'da_chot')
    or (my_role()='teacher' and is_my_lop(lop_id)   and trang_thai =  'cho_duyet')
  )
  with check (
    my_role()='admin'
    or (my_role()='owner'   and coso_id=my_coso())
    or (my_role()='teacher' and is_my_lop(lop_id))
  );
create policy ddd_del on public.duyet_diem_danh for delete to authenticated
  using (my_role()='admin');

-- ============================================================
-- 4) KHÓA sửa điểm danh khi ca đã CHỐT
--    teacher + owner KHÔNG được thêm/sửa/xóa điểm danh của ca đã chốt;
--    admin vẫn được (admin là người chốt/mở khóa cuối cùng).
-- ============================================================

-- ----- diem_danh_hv (giữ nguyên policy SELECT của GĐ3; chỉ viết lại ghi) -----
drop policy if exists dd_ins on public.diem_danh_hv;
drop policy if exists dd_upd on public.diem_danh_hv;
drop policy if exists dd_del on public.diem_danh_hv;
create policy dd_ins on public.diem_danh_hv for insert to authenticated
  with check (
    my_role()='admin'
    or ( ( (my_role()='owner' and coso_id=my_coso()) or (my_role()='teacher' and is_my_lop(lop_id)) )
         and not is_ca_chot(lop_id, ngay) )
  );
create policy dd_upd on public.diem_danh_hv for update to authenticated
  using (
    my_role()='admin'
    or ( ( (my_role()='owner' and coso_id=my_coso()) or (my_role()='teacher' and is_my_lop(lop_id)) )
         and not is_ca_chot(lop_id, ngay) )
  )
  with check (
    my_role()='admin'
    or ( ( (my_role()='owner' and coso_id=my_coso()) or (my_role()='teacher' and is_my_lop(lop_id)) )
         and not is_ca_chot(lop_id, ngay) )
  );
create policy dd_del on public.diem_danh_hv for delete to authenticated
  using (
    my_role()='admin'
    or ( ( (my_role()='owner' and coso_id=my_coso()) or (my_role()='teacher' and is_my_lop(lop_id)) )
         and not is_ca_chot(lop_id, ngay) )
  );

-- ----- cham_cong_gv (tương tự) -----
drop policy if exists cc_ins on public.cham_cong_gv;
drop policy if exists cc_upd on public.cham_cong_gv;
drop policy if exists cc_del on public.cham_cong_gv;
create policy cc_ins on public.cham_cong_gv for insert to authenticated
  with check (
    my_role()='admin'
    or ( ( (my_role()='owner' and coso_id=my_coso()) or (my_role()='teacher' and is_my_lop(lop_id)) )
         and not is_ca_chot(lop_id, ngay) )
  );
create policy cc_upd on public.cham_cong_gv for update to authenticated
  using (
    my_role()='admin'
    or ( ( (my_role()='owner' and coso_id=my_coso()) or (my_role()='teacher' and is_my_lop(lop_id)) )
         and not is_ca_chot(lop_id, ngay) )
  )
  with check (
    my_role()='admin'
    or ( ( (my_role()='owner' and coso_id=my_coso()) or (my_role()='teacher' and is_my_lop(lop_id)) )
         and not is_ca_chot(lop_id, ngay) )
  );
create policy cc_del on public.cham_cong_gv for delete to authenticated
  using (
    my_role()='admin'
    or ( ( (my_role()='owner' and coso_id=my_coso()) or (my_role()='teacher' and is_my_lop(lop_id)) )
         and not is_ca_chot(lop_id, ngay) )
  );

-- 5) Bật realtime cho bảng duyệt
do $$ begin
  begin execute 'alter publication supabase_realtime add table public.duyet_diem_danh';
  exception when others then null; end;
end $$;

-- ============================================================
-- XONG. Bấm Run. (Chưa thấy gì đổi là ĐÚNG — tới khi em cập nhật giao
-- diện Giai đoạn 2 mới có nút Gửi đối soát / Chấp nhận / Chốt.)
-- ============================================================
