-- ══════════════════════════════════════════════════════════════════════════
-- GIAI ĐOẠN 13 — CHO PHÉP KHÔI PHỤC DỮ LIỆU GIỮ NGUYÊN MÃ SỐ CŨ
--
-- VÌ SAO PHẢI LÀM (phát hiện ngày 15/08/2026 khi thử bộ sao lưu):
--   4 bảng quan trọng nhất khai mã số là "generated ALWAYS as identity".
--   Kiểu này CHẶN việc chèn lại mã số cũ — thử nạp lại một dòng thì máy chủ
--   trả về:
--       428C9  Column "id" is an identity column defined as GENERATED ALWAYS.
--
--   Hậu quả nếu để nguyên: lỡ mất dữ liệu thì KHÔNG khôi phục được nguyên
--   trạng. Nạp lại mà không giữ mã số cũ còn TỆ HƠN mất: mỗi học sinh bị
--   đánh số mới, trong khi điểm danh (diem_danh_hv.hv_id) và phiếu thu
--   (so_quy.hv_id) vẫn trỏ theo mã số cũ — tiền của em này nhảy sang em kia,
--   không cách nào lần lại được.
--
--   Đã dò thẳng trên CSDL đang chạy, kết quả:
--     ❌ hoc_vien · so_quy · diem_danh_hv · cham_cong_gv   ← bị chặn
--     ✅ duyet_diem_danh · giao_vien · lop_hoc · ca_hoc · lich_lop ·
--        co_so · thong_bao                                  ← vốn đã nạp lại được
--
-- LỆNH NÀY CÓ AN TOÀN KHÔNG:
--   Có. Nó chỉ đổi CÁCH SINH mã số cho các dòng THÊM MỚI sau này, không
--   sửa, không xóa, không di chuyển một dòng dữ liệu nào. App vẫn chạy y
--   nguyên vì app chưa bao giờ tự đặt mã số — nó luôn để máy chủ đánh số.
--   Chạy trong lúc đang vận hành cũng được, khóa bảng chỉ trong tích tắc.
--   Muốn quay lại như cũ: xem KHỐI 4 ở cuối file.
-- ══════════════════════════════════════════════════════════════════════════


-- ══════════════════════════════════════════════════════════════════════════
-- KHỐI 1 — CHỈ XEM, KHÔNG SỬA GÌ. Chạy trước để biết bảng nào đang bị chặn.
-- ══════════════════════════════════════════════════════════════════════════
select table_name  as bang,
       column_name as cot,
       identity_generation as kieu_sinh_ma,
       case identity_generation
         when 'ALWAYS'  then '❌ chặn — khôi phục sẽ hỏng'
         when 'BY DEFAULT' then '✅ khôi phục được'
       end as tinh_trang
from   information_schema.columns
where  table_schema = 'public' and is_identity = 'YES'
order  by identity_generation, table_name;


-- ══════════════════════════════════════════════════════════════════════════
-- KHỐI 2 — MỞ KHÓA. Chạy sau khi KHỐI 1 cho thấy có bảng ❌.
-- Tự tìm mọi cột đang bị chặn rồi mở, nên chạy lại nhiều lần cũng vô hại.
-- ══════════════════════════════════════════════════════════════════════════
do $$
declare r record; n int := 0;
begin
  for r in
    select table_name, column_name
    from   information_schema.columns
    where  table_schema = 'public'
      and  is_identity = 'YES'
      and  identity_generation = 'ALWAYS'
    order  by table_name
  loop
    execute format('alter table public.%I alter column %I set generated by default',
                   r.table_name, r.column_name);
    raise notice 'Đã mở: %.%', r.table_name, r.column_name;
    n := n + 1;
  end loop;
  if n = 0 then raise notice 'Không có bảng nào bị chặn — đã mở từ trước rồi.';
  else raise notice '=> Đã mở % cột. Giờ khôi phục giữ được mã số cũ.', n;
  end if;
end $$;

-- Chạy lại KHỐI 1 để xác nhận: cột "tinh_trang" phải toàn ✅.


-- ══════════════════════════════════════════════════════════════════════════
-- KHỐI 3 — CHỈ CHẠY NGAY SAU KHI VỪA KHÔI PHỤC DỮ LIỆU.
--
-- Sau khi nạp lại các dòng cũ, bộ đếm mã số của máy chủ vẫn đứng ở số thấp.
-- Không chỉnh thì học sinh ghi danh tiếp theo sẽ bị cấp mã số đã có
-- => báo lỗi trùng khóa chính. Khối này đẩy bộ đếm vượt qua mã số lớn nhất.
-- Lúc bình thường KHÔNG cần chạy.
-- ══════════════════════════════════════════════════════════════════════════
do $$
declare r record; mx bigint; seq text;
begin
  for r in
    select table_name, column_name
    from   information_schema.columns
    where  table_schema = 'public' and is_identity = 'YES'
    order  by table_name
  loop
    seq := pg_get_serial_sequence('public.' || quote_ident(r.table_name), r.column_name);
    if seq is null then continue; end if;
    execute format('select coalesce(max(%I), 0) from public.%I', r.column_name, r.table_name) into mx;
    perform setval(seq, greatest(mx, 1));
    raise notice 'Bộ đếm %.% đặt lại về %', r.table_name, r.column_name, greatest(mx, 1);
  end loop;
end $$;


-- ══════════════════════════════════════════════════════════════════════════
-- KHỐI 4 — QUAY LẠI NHƯ CŨ (chỉ dùng nếu đổi ý, không cần trong vận hành)
-- ══════════════════════════════════════════════════════════════════════════
-- alter table public.hoc_vien     alter column id set generated always;
-- alter table public.so_quy       alter column id set generated always;
-- alter table public.diem_danh_hv alter column id set generated always;
-- alter table public.cham_cong_gv alter column id set generated always;
