-- ============================================================
-- AVATAR — Giai đoạn 6: LỊCH DẠY THEO CA
--
-- Mục tiêu: mỗi cơ sở có KHUNG CA riêng (mặc định 5 ca, mỗi ca 2 giờ);
-- mỗi lớp khai học THỨ nào - CA nào - PHÒNG nào. Từ đó app biết
-- "hôm nay cơ sở có những ca nào", in được danh sách điểm danh từng ca
-- và đối soát theo ca.
--
-- Chạy 1 lần trong Supabase → SQL Editor → Run. An toàn chạy lại nhiều lần.
-- KHÔNG đụng tới dữ liệu điểm danh / chấm công / sổ quỹ đang có.
-- ============================================================

-- ------------------------------------------------------------
-- 1) KHUNG CA CỦA TỪNG CƠ SỞ
--    Mỗi cơ sở tự khai giờ ca của mình: trung tâm 5 ca × 2 giờ,
--    mầm non 4 ca ngắn 55 phút, trường liên kết mỗi nơi một khác.
-- ------------------------------------------------------------
create table if not exists public.ca_hoc (
  id      bigint generated by default as identity primary key,
  coso_id int  not null,
  ma      int  not null,                 -- số hiệu ca trong ngày: 1, 2, 3…
  ten     text,                          -- "Ca 1", "Ca sáng"…
  gio_bd  text,                          -- giờ bắt đầu, dạng "07:00"
  gio_kt  text,                          -- giờ kết thúc, dạng "09:00"
  created_at timestamptz default now(),
  unique (coso_id, ma)
);
create index if not exists ch_coso_idx on public.ca_hoc(coso_id);
alter table public.ca_hoc enable row level security;

-- ------------------------------------------------------------
-- 2) LỊCH HỌC CỦA TỪNG LỚP
--    thu: 2..7 = Thứ Hai..Thứ Bảy, 8 = Chủ nhật
--    Một dòng = "lớp này học thứ X, ca Y, tại phòng Z".
-- ------------------------------------------------------------
create table if not exists public.lich_lop (
  id      bigint generated by default as identity primary key,
  lop_id  int  not null,
  coso_id int  not null,
  thu     int  not null check (thu between 2 and 8),
  ca_ma   int  not null,
  phong   text,
  created_at timestamptz default now(),
  unique (lop_id, thu, ca_ma)
);
create index if not exists ll_coso_idx on public.lich_lop(coso_id);
create index if not exists ll_lop_idx  on public.lich_lop(lop_id);
alter table public.lich_lop enable row level security;

-- ------------------------------------------------------------
-- 3) RLS — viết ĐỦ vai trò trong mọi nhánh (đúng chuẩn đã rà 30/07/2026)
--    ca_hoc  : ai cũng ĐỌC được khung giờ cơ sở mình (GV cần biết ca mấy giờ);
--              chỉ Quản trị + Lễ tân cơ sở đó mới SỬA.
--    lich_lop: Quản trị xem/sửa tất cả; Lễ tân xem/sửa cơ sở mình;
--              Giáo viên CHỈ XEM lịch của lớp mình phụ trách.
-- ------------------------------------------------------------
drop policy if exists ch_sel on public.ca_hoc;
drop policy if exists ch_ins on public.ca_hoc;
drop policy if exists ch_upd on public.ca_hoc;
drop policy if exists ch_del on public.ca_hoc;
create policy ch_sel on public.ca_hoc for select to authenticated
  using (my_role()='admin' or ((my_role()='owner' or my_role()='teacher') and coso_id=my_coso()));
create policy ch_ins on public.ca_hoc for insert to authenticated
  with check (my_role()='admin' or (my_role()='owner' and coso_id=my_coso()));
create policy ch_upd on public.ca_hoc for update to authenticated
  using      (my_role()='admin' or (my_role()='owner' and coso_id=my_coso()))
  with check (my_role()='admin' or (my_role()='owner' and coso_id=my_coso()));
create policy ch_del on public.ca_hoc for delete to authenticated
  using (my_role()='admin' or (my_role()='owner' and coso_id=my_coso()));

drop policy if exists ll_sel on public.lich_lop;
drop policy if exists ll_ins on public.lich_lop;
drop policy if exists ll_upd on public.lich_lop;
drop policy if exists ll_del on public.lich_lop;
create policy ll_sel on public.lich_lop for select to authenticated
  using (my_role()='admin' or (my_role()='owner' and coso_id=my_coso()) or (my_role()='teacher' and is_my_lop(lop_id)));
create policy ll_ins on public.lich_lop for insert to authenticated
  with check (my_role()='admin' or (my_role()='owner' and coso_id=my_coso()));
create policy ll_upd on public.lich_lop for update to authenticated
  using      (my_role()='admin' or (my_role()='owner' and coso_id=my_coso()))
  with check (my_role()='admin' or (my_role()='owner' and coso_id=my_coso()));
create policy ll_del on public.lich_lop for delete to authenticated
  using (my_role()='admin' or (my_role()='owner' and coso_id=my_coso()));

-- ------------------------------------------------------------
-- 4) TẠO SẴN 5 CA MẶC ĐỊNH CHO 14 CƠ SỞ (id 0..13)
--    Lấy đúng khung giờ trong file "LỊCH DẠY GIÁO VIÊN.xlsx" (sheet DIỄN ĐỒNG CS2).
--    Cơ sở nào khác (mầm non…) thì vào app → Lịch học → Khung ca để sửa lại.
--    on conflict do nothing: chạy lại KHÔNG đè khung giờ cơ sở đã sửa.
-- ------------------------------------------------------------
insert into public.ca_hoc (coso_id, ma, ten, gio_bd, gio_kt)
select cs.id, v.ma, v.ten, v.bd, v.kt
from generate_series(0,13) as cs(id)
cross join (values
  (1,'Ca 1','07:00','09:00'),
  (2,'Ca 2','09:15','11:15'),
  (3,'Ca 3','14:00','16:00'),
  (4,'Ca 4','17:15','19:15'),
  (5,'Ca 5','19:30','21:30')
) as v(ma,ten,bd,kt)
on conflict (coso_id, ma) do nothing;

-- ------------------------------------------------------------
-- 5) Bật realtime (sửa lịch ở máy này, máy kia tự thấy)
-- ------------------------------------------------------------
do $$ begin
  begin execute 'alter publication supabase_realtime add table public.ca_hoc';
  exception when others then null; end;
  begin execute 'alter publication supabase_realtime add table public.lich_lop';
  exception when others then null; end;
end $$;

-- ============================================================
-- XONG. Bấm Run rồi tải lại web (Ctrl+F5).
-- Vào menu "Lịch học" để khai lịch cho từng lớp.
-- ============================================================
