-- ============================================================
-- AVATAR — Giai đoạn 8: THÔNG BÁO CỦA TRUNG TÂM
--
-- Quản trị đăng thông báo cho toàn chuỗi; Lễ tân đăng cho cơ sở mình.
-- Chọn được người nhận (tất cả / chỉ giáo viên / chỉ lễ tân), mức độ,
-- ghim lên đầu và ngày hết hạn hiển thị.
--
-- Chạy 1 lần trong Supabase → SQL Editor → Run. An toàn chạy lại nhiều lần.
-- KHÔNG đụng tới dữ liệu đang có.
-- ============================================================

create table if not exists public.thong_bao (
  id        bigint generated by default as identity primary key,
  tieu_de   text not null,
  noi_dung  text,
  muc_do    text not null default 'thuong'
            check (muc_do in ('thuong','quan_trong','khan')),
  coso_id   int,                       -- NULL = gửi toàn chuỗi
  vai_tro   text not null default 'all'
            check (vai_tro in ('all','teacher','owner')),
  ghim      boolean default false,     -- ghim lên đầu danh sách
  het_han   date,                      -- NULL = hiện mãi
  nguoi_dang text,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);
create index if not exists tb_coso_idx on public.thong_bao(coso_id);
create index if not exists tb_time_idx on public.thong_bao(created_at desc);
alter table public.thong_bao enable row level security;

-- ------------------------------------------------------------
-- RLS
--   XEM : Quản trị thấy tất cả (để quản lý).
--         Người khác chỉ thấy tin gửi toàn chuỗi HOẶC gửi đúng cơ sở mình,
--         VÀ gửi cho "tất cả" HOẶC đúng vai trò của mình.
--   ĐĂNG/SỬA/XÓA : Quản trị mọi tin; Lễ tân chỉ tin của cơ sở mình
--         (không đăng được tin toàn chuỗi — coso_id phải khác NULL).
-- ------------------------------------------------------------
drop policy if exists tb_sel on public.thong_bao;
drop policy if exists tb_ins on public.thong_bao;
drop policy if exists tb_upd on public.thong_bao;
drop policy if exists tb_del on public.thong_bao;

create policy tb_sel on public.thong_bao for select to authenticated
  using (
    my_role()='admin'
    or ( (coso_id is null or coso_id = my_coso())
         and (vai_tro = 'all' or vai_tro = my_role()) )
  );
create policy tb_ins on public.thong_bao for insert to authenticated
  with check ( my_role()='admin' or (my_role()='owner' and coso_id = my_coso()) );
create policy tb_upd on public.thong_bao for update to authenticated
  using      ( my_role()='admin' or (my_role()='owner' and coso_id = my_coso()) )
  with check ( my_role()='admin' or (my_role()='owner' and coso_id = my_coso()) );
create policy tb_del on public.thong_bao for delete to authenticated
  using ( my_role()='admin' or (my_role()='owner' and coso_id = my_coso()) );

-- ------------------------------------------------------------
-- Bật realtime: đăng tin ở máy này, giáo viên thấy ngay không cần tải lại
-- ------------------------------------------------------------
do $$ begin
  begin execute 'alter publication supabase_realtime add table public.thong_bao';
  exception when others then null; end;
end $$;

-- ------------------------------------------------------------
-- Kiểm tra
-- ------------------------------------------------------------
select
  (select count(*) from information_schema.tables
     where table_schema='public' and table_name='thong_bao')          as da_tao_bang,
  (select count(*) from pg_policies
     where schemaname='public' and tablename='thong_bao')             as so_policy,
  (select count(*) from public.thong_bao)                             as so_thong_bao;

-- ============================================================
-- XONG. Kết quả đúng: da_tao_bang = 1, so_policy = 4, so_thong_bao = 0.
-- Sau đó tải lại web (Ctrl+F5) → menu mới "Thông báo".
-- ============================================================
